export const proyectosData = [
    {
        id: 1,
        img: "https://i.ibb.co/ZH6gRGq/anime.jpg",
        name: "Buscar Anime",
        descripcion: "React, Styled Components, axios",
        github: "https://github.com/EstefaniAzocar/aplicativoAnime",
        demo: "https://aplicativo-anime.vercel.app/",

    },
    {
        id: 2,
        img: "https://i.ibb.co/fSjpn9C/apiAnime.jpg",
        name: "Api Anime",
        descripcion: "Node, Axios, Express",
        github: "https://github.com/EstefaniAzocar/apiAnime",
        demo: "",
    },
    {
        id: 3,
        img: "https://i.ibb.co/1MvXWdj/Comercializadora.jpg",
        name: "Usuario Autenticado",
        descripcion: "React, Css, Axios",
        github: "https://github.com/EstefaniAzocar/pruebaFrontend",
        demo: "",
     },
     {
        id: 4,
        img: "https://i.ibb.co/MDJ9bWR/api-Cormecializadora.jpg",
        name: "Api de Autenticar",
        descripcion: "Node, Express, Jwt, Mongoose",
        github: "https://github.com/EstefaniAzocar/aplicativoAnime",
        demo: "",
     },
     {
        id: 5,
        img: "https://i.ibb.co/z8C7kWL/burger-Queen.jpg",
        name: "Burger Queen",
        descripcion: "React, Sass, Axios",
        github: "https://github.com/EstefaniAzocar/BOG005-burger-queen-api-client/tree/main/burger-queen",
        demo: "",
    },
    {
        id: 6,
        img: "https://i.ibb.co/XWcsBJN/Social-network.jpg",
        name: "Social Network",
        descripcion: "React, Scss, Firebase ",
        github: "https://github.com/EstefaniAzocar/Social-network",
        demo: "https://knitters.netlify.app/",
    },
    {
        id: 7,
        img: "https://i.ibb.co/3C1Z8hv/tienda-Estefani.jpg",
        name: "Shopping Cart",
        descripcion: "React, Sass, Axios ",
        github: "https://github.com/EstefaniAzocar/aplicativoN5",
        demo: "https://tienda-estefani.netlify.app/",
    },
    {
        id: 8,
        img: "https://i.ibb.co/JpY3MPX/POKEVEL.jpg",
        name: "Memory Match",
        descripcion: "Html, Scss, JavaScript ",
        github: "https://github.com/EstefaniAzocar/BOG005-memory-match",
        demo: "https://pokevel.netlify.app/",
    },
   
]