export const proyectosData = [
    {
        id: 1,
        img: "https://i.ibb.co/dkkjHbX/buscar-Anime.jpg",
        name: "Buscador anime",
        descripcion: "React, axios",
        github: "https://github.com/EstefaniAzocar/aplicativoAnime",
        demo: "https://aplicativo-anime.vercel.app/",

    },
    {
        id: 2,
        img: "https://jumbocolombiaio.vtexassets.com/arquivos/ids/185701/7702084137520-1.jpg?v=637813979850670000",
        name: "Burger-Queen",
        descripcion: "React, Scss",
        github: "https://github.com/EstefaniAzocar/BOG005-burger-queen-api-client",
        demo: "",
    },
    {
        id: 3,
        img: "https://i.ibb.co/XWcsBJN/Social-network.jpg",
        name: "Social Network",
        descripcion: "React, Scss, Firebase ",
        github: "https://github.com/EstefaniAzocar/Social-network",
        demo: "https://knitters.netlify.app/",
    },
    {
        id: 4,
        img: "https://i.ibb.co/JpY3MPX/POKEVEL.jpg",
        name: "Memory Match",
        descripcion: "Html, Scss, JavaScript ",
        github: "https://github.com/EstefaniAzocar/BOG005-memory-match",
        demo: "https://pokevel.netlify.app/",
    },
    {
        id: 5,
        img: "https://jumbocolombiaio.vtexassets.com/arquivos/ids/185701/7702084137520-1.jpg?v=637813979850670000",
        name: "harina4",
        descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel sem id lorem fermentum imperdiet molestie sit amet ",
        github: "https://github.com/EstefaniAzocar/aplicativoAnime",
        demo: "https://aplicativo-anime.vercel.app/",
    }   ,
    {
        id: 6,
        img: "https://jumbocolombiaio.vtexassets.com/arquivos/ids/185701/7702084137520-1.jpg?v=637813979850670000",
        name: "harina5",
        descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel sem id lorem fermentum imperdiet molestie sit amet ",
        github: "https://github.com/EstefaniAzocar/aplicativoAnime",
        demo: "https://aplicativo-anime.vercel.app/",
     },
]